variables:
  IMAGE_TAG: v$CI_PIPELINE_ID
  AR_IMAGE: LOCATION-docker.pkg.dev/PROJECT/REPOSITORY/landing-page

stages:
  - build
  - push
  - deploy

build-job:
  extends:
    - .runner-solarena
  stage: build
  services:
    - docker:24.0.5-dind
  image: docker:git
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG --build-arg="name=Cloud Run" .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

include:
  - component: gitlab.com/google-gitlab-components/artifact-registry/upload-artifact-registry@0.1.0
    inputs:
      extends:
        - .runner-solarena
      stage: push
      source: $CI_REGISTRY_IMAGE:$IMAGE_TAG
      target: $AR_IMAGE:$IMAGE_TAG

  - component: gitlab.com/google-gitlab-components/cloud-run/deploy-cloud-run@0.1.0
    inputs:
      extends:
        - .runner-solarena
      stage: deploy
      image: $AR_IMAGE:$IMAGE_TAG
      project_id: PROJECT
      region: LOCATION
      service: landing-page

