variables:
  IMAGE_TAG: v$CI_PIPELINE_ID
  AR_IMAGE: asia-northeast1-docker.pkg.dev/braided-hangout-438006-k2/landing-page/landing-page

stages:
  - build
  - push
  - deploy

build-job:
  extends:
    - .runner-solarena
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG --build-arg="name=Cloud Run" .

push-to-artifact-registry:
  extends:
    - .runner-solarena
  stage: push
  image: google/cloud-sdk:latest
  script:
    - echo $GCP_SERVICE_KEY | base64 -d > /tmp/gcp-key.json
    - gcloud auth activate-service-account --key-file /tmp/gcp-key.json
    - gcloud auth configure-docker asia-northeast1-docker.pkg.dev
    - docker pull $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker tag $CI_REGISTRY_IMAGE:$IMAGE_TAG $AR_IMAGE:$IMAGE_TAG
    - docker push $AR_IMAGE:$IMAGE_TAG

deploy-to-cloud-run:
  extends:
    - .runner-solarena
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo $GCP_SERVICE_KEY | base64 -d > /tmp/gcp-key.json
    - gcloud auth activate-service-account --key-file /tmp/gcp-key.json
    - gcloud run deploy landing-page 
        --image $AR_IMAGE:$IMAGE_TAG 
        --project braided-hangout-438006-k2 
        --region asia-northeast1 
        --platform managed 
        --allow-unauthenticated